# Generated by Django 5.1 on 2024-08-21 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugtrackingsystem', '0002_project_users_alter_project_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='users',
        ),
    ]
