# Generated by Django 5.1 on 2024-08-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtrackingsystem', '0007_project_developers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='developers',
            field=models.ManyToManyField(related_name='projects', to='bugtrackingsystem.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Developer', 'Developer'), ('QA', 'QA')], max_length=30),
        ),
    ]
