# Generated by Django 5.1 on 2024-08-29 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtrackingsystem', '0009_project_assigned_developers_alter_project_developers'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assigned_qas',
            field=models.ManyToManyField(limit_choices_to={'role': 'QA'}, related_name='qa_projects', to='bugtrackingsystem.userprofile'),
        ),
    ]
