# Generated by Django 5.1 on 2024-09-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtrackingsystem', '0014_bug'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots/'),
        ),
    ]
