# Generated by Django 5.1 on 2024-09-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtrackingsystem', '0016_remove_bug_assigned_developers_remove_bug_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
