# Generated by Django 5.1 on 2024-09-19 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtrackingsystem', '0017_bug_deadline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bug',
            unique_together={('title', 'project')},
        ),
        migrations.AddField(
            model_name='bug',
            name='type',
            field=models.CharField(choices=[('feature', 'Feature'), ('bug', 'Bug')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bug',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bugs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bug',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bug',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugs', to='bugtrackingsystem.project'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='bugs/screenshots/'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('started', 'Started'), ('completed', 'Completed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='bug',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='bug',
            name='created_by',
        ),
    ]
