# Generated by Django 5.1 on 2024-09-22 19:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtrackingsystem', '0019_alter_bug_deadline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='bug',
            name='assigned_to',
            field=models.ManyToManyField(related_name='assigned_bugs', to=settings.AUTH_USER_MODEL),
        ),
    ]
