# Generated by Django 5.1 on 2024-09-23 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtrackingsystem', '0020_remove_bug_assigned_to_bug_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='assigned_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_bugs', to='bugtrackingsystem.userprofile'),
            preserve_default=False,
        ),
    ]
