# Generated by Django 5.1 on 2024-09-26 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtrackingsystem', '0021_bug_assigned_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='assigned_to',
            field=models.ManyToManyField(related_name='assigned_bugs', to='bugtrackingsystem.userprofile'),
        ),
    ]
